# Generated by Django 4.2.5 on 2023-09-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, unique=True, verbose_name='Nombre Dispositivo')),
                ('cordenadaX', models.CharField(max_length=100)),
                ('cordenadaY', models.CharField(max_length=100)),
                ('consumoHora', models.CharField(max_length=100, verbose_name='Consumo por hora')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(max_length=100, verbose_name='Nombre Usuario')),
                ('correoElectronico', models.EmailField(max_length=50, unique=True, verbose_name='Correo Electrónico')),
                ('contraseña', models.CharField(max_length=20, unique=True, verbose_name='Contraseña')),
            ],
        ),
    ]
