# Generated by Django 4.2.5 on 2023-09-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('cordenadaX', models.CharField(max_length=100)),
                ('cordenadaY', models.CharField(max_length=100)),
                ('consumoHora', models.CharField(max_length=100)),
            ],
        ),
    ]
