# Generated by Django 4.2.5 on 2023-09-25 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('idComuna', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('nombreComuna', models.CharField(max_length=200, verbose_name='Comuna')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioUso',
            fields=[
                ('idHorarioUso', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('idPropiedad', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('nombrePropiedad', models.CharField(max_length=200, verbose_name='Nombre de la Propiedad')),
                ('direccionPropiedad', models.CharField(max_length=200, verbose_name='Dirección')),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('idProvincia', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('nombreProvincia', models.CharField(max_length=200, verbose_name='Provincia')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('idRegion', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('nombreRegion', models.CharField(max_length=200, verbose_name='Región')),
            ],
        ),
        migrations.CreateModel(
            name='Sectores',
            fields=[
                ('idSector', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('nombreSector', models.CharField(max_length=200, verbose_name='Nombre del Sector')),
                ('metrosCuadrados', models.FloatField(max_length=15, verbose_name='Metros^2')),
            ],
        ),
        migrations.CreateModel(
            name='TipoSector',
            fields=[
                ('idSector', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('tipoSector', models.CharField(max_length=200, verbose_name='Tipo Sector')),
            ],
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='idUsuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.usuario'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='consumoHora',
            field=models.CharField(help_text='EN KW', max_length=100, verbose_name='Consumo por hora'),
        ),
        migrations.CreateModel(
            name='TipoDispositivo',
            fields=[
                ('idTipoDispositivo', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('tipoDispositivo', models.CharField(max_length=200, verbose_name='Tipo Dispositivo')),
                ('idDispo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.dispositivo')),
            ],
        ),
    ]
