# Generated by Django 4.2.5 on 2023-09-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(max_length=100, verbose_name='Nombre Usuario')),
                ('correoElectronico', models.EmailField(max_length=50, unique=True, verbose_name='Correo Electrónico')),
                ('contraseña', models.CharField(max_length=20, unique=True, verbose_name='Contraseña')),
            ],
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='consumoHora',
            field=models.CharField(max_length=100, verbose_name='Consumo por hora'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='titulo',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
