# Generated by Django 4.2.5 on 2023-09-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('idComuna', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('nombreComuna', models.CharField(max_length=200, verbose_name='Comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('idProvincia', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('nombreProvincia', models.CharField(max_length=200, verbose_name='Provincia')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('idRegion', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('nombreRegion', models.CharField(max_length=200, verbose_name='Región')),
            ],
        ),
    ]
