# Generated by Django 4.2.5 on 2023-09-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_comuna_provincia_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('idPropiedad', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('nombrePropiedad', models.CharField(max_length=200, verbose_name='Nombre de la Propiedad')),
                ('direccionPropiedad', models.CharField(max_length=200, verbose_name='Dirección')),
            ],
        ),
        migrations.CreateModel(
            name='Sectores',
            fields=[
                ('idSector', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('nombreSector', models.CharField(max_length=200, verbose_name='Nombre del Sector')),
                ('metrosCuadrados', models.FloatField(max_length=15, verbose_name='Metros^2')),
            ],
        ),
    ]
