# Generated by Django 4.2.5 on 2023-09-25 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_comuna_horariouso_propiedad_provincia_region_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comuna',
        ),
    ]
