# Generated by Django 4.2.5 on 2023-09-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_propiedad_sectores'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioUso',
            fields=[
                ('idHorarioUso', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDispositivo',
            fields=[
                ('idTipoDispositivo', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('tipoDispositivo', models.CharField(max_length=200, verbose_name='Tipo Dispositivo')),
            ],
        ),
        migrations.CreateModel(
            name='TipoSector',
            fields=[
                ('idSector', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('tipoSector', models.CharField(max_length=200, verbose_name='Tipo Sector')),
            ],
        ),
    ]
