# Generated by Django 4.2.5 on 2023-09-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_dispositivo_idusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='consumoHora',
            field=models.CharField(help_text='EN KW', max_length=100, verbose_name='Consumo por hora'),
        ),
    ]
